name: pick_office
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^1.0.3
  freezed_annotation: ^1.1.0

  go_router: ^3.0.7
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.2
  dart_code_metrics: ^4.9.1

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  freezed: ^1.1.1
  hive_generator: ^1.1.2
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/data/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: GT Walsheim Pro
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/GTWalsheimPro-Regular.ttf
          weight: 400
